services:
  - type: web
    name: e-calculator
    runtime: python
    plan: free

    branch: dev
    rootDir: E_Calculator

    buildCommand: ./build.sh

    startCommand: gunicorn E_Calculator.asgi:application -k uvicorn.workers.UvicornWorker

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: E_Calculator.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: e-calculator.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
