services:
  - type: web
    name: e-calculator
    runtime: python
    plan: free

    branch: dev
    rootDir: E_Calculator

    pythonVersion: 3.11.9

    buildCommand: ./build.sh

    startCommand: gunicorn E_Calculator.asgi:application -k uvicorn.workers.UvicornWorker

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: E_Calculator.settings
      - key: DATABASE_URL
        fromDatabase:
          name: e_calculator
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
